SUPABASE_URL = "https://mgggmukpobhmbwelxnkd.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "sb_secret_fp4Yo4GIJWwjve2aS8VZpg_tsd4nS1r"

PLAN_ID = "b102b5d9-a890-468d-996e-9720f1a39a09"

EDIT_TOKEN = "ILkoep1yVB5SMrQj"
